name: Blastula Blasting Email
run-name: ${{ github.actor }} is sending an email from the organizers.science addres
on: [push]

jobs:
  import-data:
    runs-on: ubuntu-latest
    steps:
      - name: sSet up R
        uses: r-lib/actions/setup-r@v2
        
      - name: Install Packages
        uses: r-lib/actions/setup-r-dependencies@v2
          with:
            packages: |
              any::tidyverse
              any::blastula
              any::here
              any::glue
        echo: "Packages installed successfully."