name: Blastula Blasting Email
run-name: ${{ github.actor }} is sending an email from the organizers.science address
on: [push]

jobs:
  import-data:
    runs-on: ubuntu-latest
    steps:
      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Check Repo
        uses: actions/checkout@v3
        - run: echo "The ${{ github.repository }} repository has been cloned!⏱️"

      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}

      - name: Test Script
        run: Rscript -e "source('scripts/test.R')"